codingBottle/codingBottle-MOBILE

week01/week02_hyunryeol.md

1주차 스터디 과제 제출
final private 사용하면서도 어떠한 상황에서 사용하는게 합리적인 것에 대해
조금 더 생각해볼 수 있던 기회였던 것 같아요

[week01] hyunryeol 과제 제출

---

week02/week02_hanni.md

week 02 파트 질문 관련 정리
- delegate
- protocol
- subscript
- instance method vs class method

[week02] hanni 과제 제출

---

week03/week03_psy.md

[week03] psy 과제 제출

---

week03/week03_nahyun.md

[week03] nahyun 과제 제출

---

week04/week04_hyunryeol.md

4주차 과제 제출
nil 과 null의 차이점에 대해 알았어요! 
처음 접한 블로그가 null을 쓰려다가 오타가 생겨서 nil 이라고 적은 줄 알았는데 아니더라고요

[week04] hyunryeol 과제 제출

---

week04/week04_rose.md

mutating 키워드에 대해 설명하시오.
탈출 클로저에 대하여 설명하시오.
Optional 이란 무엇인지 설명하시오.
MVC 구조에 대해 블록 그림을 그리고, 각 역할과 흐름을 설명하시오.

[week04] rose 과제 제출

---

week04/week04_ino.md

[week04] ino 과제 제출

---

week04/week04_psy.md

[week04] psy 과제 제출

---

week04/week04_question.md
week05/week05_question.md

- week04_question title 수정 및 week05 ad list 추가

[week05] add AD List 

---

week05/week05_rose.md

- 옵저버 패턴에 대해 설명하시오.
- Delegation와 Notification 방식의 차이점에 대해 설명하시오.

[week05] rose 과제 제출

---

week05/week05_ino.md

옵저버 패턴에 대해 설명하시오.
Delegation와 Notification 방식의 차이점에 대해 설명하시오.

[week05] ino 과제 제출

---

week05/week05_hyunryeol.md

week05 AD
옵저버 패턴에 대해 설명하시오.
Delegation와 Notification 방식의 차이점에 대해 설명하시오.

[week05] hyunryeol 과제 제출

---

week05/week05_nahyun.md

- 옵저버 패턴에 대해 설명하시오.
- Delegation와 Notification 방식의 차이점에 대해 설명하시오.

[week05] nahyun 과제 제출

---

week07/week07_hyunryeol.md

- Safearea에 대해서 설명하시오.
- Left Constraint 와 Leading Constraint 의 차이점을 설명하시오.

[week07] hyunryeol 과제 제출

---

week07/week07.psy.md

- Safearea에 대해서 설명하시오.
- Left Constraint 와 Leading Constraint의 차이점을 설명하시오.

[week07] psy 과제 제출

---

week07/week07_nahyun.md

- Safearea에 대해서 설명하시오.
- Left Constraint 와 Leading Constraint 의 차이점을 설명하시오.

[week07] nahyun 과제 제출

---

week10/week10_hyunryeol.md

[week10] hyunryeol 과제 제출

---

week10/week10_rose.md

[week10] rose 과제 제출

---

week10/week10_ino.md

[week10] ino 과제 제출

---

week11/week11_psy.md

- 알고리즘 문제 풀이
- Set은 순서를 고려하지 않는 데이터 구조이기에, 원소의 순서나 중복 여부는 고려하지 않고, 원소의 존재 여부만을 판단하기에 위와 같은 풀이가 가능하다.

[week11] psy 과제 제출

---

week10/week10_hyunryeol.md
week11/week11_hyunryeol.md

알고리즘 과제제출
## 📚 새로 알게 된 내용 혹은 공유하고 싶은 내용

[week11] ryeol 과제 제출

---

week11/week11_ino.md

[week11] ino 과제 제출 

---

week11/week11_rose.md

[week11] rose 과제 제출

---

week12/week12_psy.md

- 알고리즘 풀이 과제
- Array의 replaceSubrange 메서드 사용법

[week12] psy 과제 제출

---

week12/week12_ino.md

알고리즘 과제 제출
prefix, suffix 사용 방법

[week12] ino 과제 제출

---

week11/week12/week12_nahyun.md

[week12] nahyun 과제 제출

---

week12/week12_hyunryeol.md

[week12] hyunryeol 과제 제출

---

week13/week13 _ino.md

알고리즘 과제 제출
prefix 함수에 클로져를 이용해서 count를 가져오는 방법.  클로져를 잘 활용하는 방법

[week13] ino 과제 제출

---

week13/week13_psy.md

[week13] psy 과제 제출

---

week13/week13_rose.md

[week13] rose 과제 제출
